[package]
name = "genver"
version = "0.1.0"
authors = ["pSox <pSox-genver(a)st8l.com>"]

[dependencies]
clippy = { version = "*", optional = true }
config = { version = "*" }
clap = { version = "*" }
